# Generated by Django 4.0.4 on 2022-04-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dari', '0008_category_image_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='category/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
    ]
