# Generated by Django 4.0.1 on 2022-05-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dari', '0010_purchase_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='update_date',
            field=models.DateField(auto_now=True),
        ),
    ]
