# Generated by Django 4.0.4 on 2022-05-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dari', '0011_product_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='total_price',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
